name: Build and Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t akashv1212/flask-ml-app:latest .

    - name: Push Docker image
      run: |
        docker push akashv1212/flask-ml-app:latest

    - name: SSH to Swarm Manager and update service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SWARM_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker service update --image akashv1212/flask-ml-app:latest flask-ml-app

    - name: Set up SSH key
      run: |
       mkdir -p ~/.ssh
       echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa
       ssh-keyscan <server-ip> >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no akashvikram98@your.server.ip.address "echo Connected!"

