name: Train Model

on:
  push:
    branches: [production]
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Training
        run: python app/model/train.py
      - name: Run Tests
        run: python app/model/test_train.py
